apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: controller-deployment
spec:
  template:
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.cn-shenzhen.aliyuncs.com/shikanon/ml-pipeline.viewer-crd-controller:0.1.23
        imagePullPolicy: IfNotPresent
        name: ml-pipeline-viewer-controller
      serviceAccountName: crd-service-account
