namespace: kubeflow
resources:
- metrics-collector-rbac.yaml
- metrics-collector-template-configmap.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: registry.cn-shenzhen.aliyuncs.com/shikanon/kubeflow-images-public.katib.v1alpha2.metrics-collector
    newTag: v0.1.2-alpha-289-g14dad8b


