apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: katib-suggestion-bayesianoptimization
  labels:
    app: katib
    component: suggestion-bayesianoptimization
spec:
  replicas: 1
  template:
    metadata:
      name: katib-suggestion-bayesianoptimization
      labels:
        app: katib
        component: suggestion-bayesianoptimization
    spec:
      containers:
      - name: katib-suggestion-bayesianoptimization
        image: registry.cn-shenzhen.aliyuncs.com/shikanon/kubeflow-images-public.katib.suggestion-bayesianoptimization:v0.6.0-rc.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: api
          containerPort: 6789
